name = "End2EndThermalImg"
uuid = "9877574d-29c9-40c6-9182-d79fa7730244"
authors = ["Sophie <fisher.soph@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastChebInterp = "cf66c380-9a80-432c-aff8-4f9c79c0bdde"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StochasticAD = "e4facb34-4f7e-4bec-b153-e122c37934ac"

[compat]
BenchmarkTools = "1.5.0"
CSV = "0.10.15"
CondaPkg = "0.2.24"
DataFrames = "1.7.0"
DelimitedFiles = "1.9.1"
Distributions = "0.25.113"
FastChebInterp = "1.2.0"
Interpolations = "0.15.1"
Parameters = "0.12.3"
PythonCall = "0.9.23"
julia = "1.10.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
